### ISSUE TITLE
Using ometa-js for syntax highlighting with CodeMirror

### ISSUE THREAD

**Issue by emertechie** [veged/ometa-js#23]
I'd like to use ometa-js with codemirror.net to provide syntax highlighting for any ometa grammar.

Ideally I'd like to parse any grammar and produce a list of rule name matches and their position in the input. Is this currently possible and if not, what's best approach to doing so? I'm willing to try add this & submit pull request

Similar thing done here: https://github.com/Page-/ometa-js/blob/highlighting/lib/codemirror-ometa/highlighter.js

**Comment by indutny** [comment]
Surely, its possible. Please take a look at https://github.com/veged/ometa-js/blob/nodejs/test/unit/parser-test.js and https://github.com/veged/ometa-js/blob/nodejs/test/fixtures/common.js#L62-L66 .

Basically, you'll need to run something like this in order to get AST: `require('ometajs').parser.create(code).execute()`.
